import NavigationMenu from "@/Components/NavigtionMenu/NavigationMenu";
import "./globals.css";


export const metadata = {
  title: "IT HelpDesk Service Team CRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className='mainLayoutContainer'>
          <div><NavigationMenu/></div>
        <div className="mainLayoutChildren">{children}</div>
        </section>
      </body>
    </html>
  );
}
